version: '3'
services:
  db:
    image: postgres
    ports:
      - "5433:5433"
  redis:
    image: redis:3.2.4-alpine
    ports:
      - 6379:6379
    command: redis-server --appendonly yes
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
